name: Semgrep

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: pip install semgrep==1.165.0
      - run: semgrep --config=p/javascript --config=p/typescript --error .
